# Generated by Django 3.2.8 on 2021-10-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('razaosocial', models.CharField(blank=True, db_column='razaoSocial', max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('end_point', models.CharField(blank=True, max_length=100, null=True)),
                ('dnscloudaws', models.CharField(blank=True, max_length=255, null=True)),
                ('datapadrao', models.CharField(blank=True, max_length=1, null=True)),
                ('ultimaatualizacao', models.DateTimeField(blank=True, null=True)),
                ('idcontador_fk', models.IntegerField(blank=True, db_column='idContador_FK', null=True)),
                ('versaousada', models.CharField(blank=True, db_column='versaoUsada', max_length=20, null=True)),
                ('nomebasedadoscloud', models.CharField(blank=True, max_length=255, null=True)),
                ('licencaativa', models.CharField(blank=True, db_column='licencaAtiva', max_length=1, null=True)),
                ('versaofull', models.CharField(blank=True, db_column='versaoFull', max_length=1, null=True)),
                ('uf', models.CharField(blank=True, db_column='UF', max_length=3, null=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=255, null=True)),
                ('qtde_backoffice', models.IntegerField(blank=True, db_column='Qtde_BackOffice', null=True)),
                ('qtde_pc', models.IntegerField(blank=True, db_column='Qtde_Pc', null=True)),
                ('qtde_micro_terminais', models.IntegerField(blank=True, db_column='Qtde_Micro_Terminais', null=True)),
                ('qtde_mobile', models.IntegerField(blank=True, db_column='Qtde_Mobile', null=True)),
                ('qtde_caixa', models.IntegerField(blank=True, db_column='Qtde_Caixa', null=True)),
                ('qtde_administrativo', models.IntegerField(blank=True, db_column='Qtde_Administrativo', null=True)),
                ('qtde_touch', models.IntegerField(blank=True, db_column='Qtde_Touch', null=True)),
                ('qtde_recepcao', models.IntegerField(blank=True, db_column='Qtde_Recepcao', null=True)),
                ('qtde_forcadevendas', models.IntegerField(blank=True, db_column='Qtde_ForcaDeVendas', null=True)),
                ('qtde_terminaldesaida', models.IntegerField(blank=True, db_column='Qtde_TerminalDeSaida', null=True)),
                ('qtde_terminaldeproducao', models.IntegerField(blank=True, db_column='Qtde_TerminalDeProducao', null=True)),
                ('qtde_moduloremoto', models.IntegerField(blank=True, db_column='Qtde_ModuloRemoto', null=True)),
                ('datahoraultimobackup', models.DateTimeField(blank=True, db_column='dataHoraUltimoBackup', null=True)),
                ('valortotalliquidototal', models.FloatField(blank=True, db_column='valorTotalLiquidoTOTAL', null=True)),
                ('qtdecomandaspagastotal', models.IntegerField(blank=True, db_column='qtdeComandasPagasTOTAL', null=True)),
                ('ticketmedioglobalatual', models.FloatField(blank=True, db_column='ticketMedioGlobalAtual', null=True)),
                ('valorsf', models.FloatField(blank=True, db_column='valorSF', null=True)),
                ('percsf', models.FloatField(blank=True, db_column='percSF', null=True)),
                ('bloquearsf', models.CharField(blank=True, db_column='bloquearSF', max_length=1, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosFuncoesAdm',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('login', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.CharField(blank=True, max_length=1, null=True)),
                ('acessobackupbd', models.CharField(blank=True, db_column='acessoBackupBD', max_length=1, null=True)),
                ('acessodownloadnotas', models.CharField(blank=True, db_column='acessoDownloadNotas', max_length=1, null=True)),
            ],
            options={
                'db_table': 'usuarios_funcoes_adm',
                'managed': False,
            },
        ),
    ]
