# Generated by Django 3.2.7 on 2021-11-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelamento',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('qtdecomanda', models.IntegerField(blank=True, null=True)),
                ('qtdeitens', models.IntegerField(blank=True, null=True)),
                ('qtdeadicionais', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cancelamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('itensvenda', models.FloatField(blank=True, null=True)),
                ('descitensvenda', models.FloatField(blank=True, null=True)),
                ('servico', models.FloatField(blank=True, null=True)),
                ('adicional', models.FloatField(blank=True, null=True)),
                ('desconto', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('qtdepessoa', models.IntegerField(blank=True, null=True)),
                ('totalestimado', models.FloatField(blank=True, null=True)),
                ('totalqtdepessoa', models.IntegerField(blank=True, null=True)),
                ('totalcomandas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comanda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contadores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=30, null=True)),
                ('crc', models.CharField(blank=True, max_length=50, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'contadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('qtdeitens', models.IntegerField(blank=True, null=True)),
                ('qtdeadicionais', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'desconto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logbd',
            fields=[
                ('idlog', models.AutoField(primary_key=True, serialize=False)),
                ('datahora', models.DateTimeField(blank=True, null=True)),
                ('bancodados', models.CharField(blank=True, db_column='bancoDados', max_length=255, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'logbd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('livre', models.IntegerField(blank=True, null=True)),
                ('aberta', models.IntegerField(blank=True, null=True)),
                ('emconta', models.IntegerField(blank=True, null=True)),
                ('ticketmedio', models.FloatField(blank=True, null=True)),
                ('ativas', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('totalcancelamento', models.FloatField(blank=True, null=True)),
                ('totaldesconto', models.FloatField(blank=True, null=True)),
                ('totalsangria', models.FloatField(blank=True, null=True)),
                ('totalreforco', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ocorrencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermissoesNumeros',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_telefone', models.CharField(blank=True, max_length=45, null=True)),
                ('access_token', models.IntegerField(blank=True, null=True)),
                ('qtd_sms_enviada', models.CharField(blank=True, max_length=1, null=True)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('data_primeira_solicitacao', models.DateTimeField(blank=True, null=True)),
                ('data_ultima_solicitacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permissoes_numeros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecebimentoCaixa',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('totalrecebido', models.FloatField(blank=True, null=True)),
                ('totalreceber', models.FloatField(blank=True, null=True)),
                ('caixasabertos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recebimento_caixa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reforco',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('qtdetroco', models.IntegerField(blank=True, null=True)),
                ('totaltroco', models.FloatField(blank=True, null=True)),
                ('qtdependura', models.IntegerField(blank=True, null=True)),
                ('totalpendura', models.FloatField(blank=True, null=True)),
                ('qtdecreditocliente', models.IntegerField(blank=True, null=True)),
                ('totalcreditocliente', models.FloatField(blank=True, null=True)),
                ('qtdecreditoprepago', models.IntegerField(blank=True, null=True)),
                ('totalcreditoprepago', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reforco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sangria',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('qtde', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sangria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Syncrealtime',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('idempresa_fk', models.IntegerField(blank=True, db_column='idEmpresa_Fk', null=True)),
                ('datahoraultimaverificacao', models.DateTimeField(blank=True, db_column='dataHoraUltimaVerificacao', null=True)),
                ('quantidadenotasparadas', models.CharField(blank=True, db_column='QuantidadeNotasParadas', max_length=10, null=True)),
            ],
            options={
                'db_table': 'syncrealtime',
                'managed': False,
            },
        ),
    ]
